<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <OutputType Condition="$([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('win-'))">WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../SamsungController.Desktop/SamsungController.Desktop.csproj" /></ItemGroup>
</Project>
